#!/usr/bin/env python3
"""Manage which paper-library PDF blocks are tracked or fetched.

Edit PUSH_PDFS and PULL_PDFS below. Keep a block False to make PDFs in that
folder local-only; set it True when that folder's PDFs should be pushed/fetched.

The script always keeps Markdown and text metadata tracked.
"""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

TAG_DIRS = [
    "Perceptive",
    "Locomotion",
    "Navigation",
    "Loco_Manipulation",
    "Motion_Tracking",
    "Teleoperation_Data",
    "Motion_Generation",
    "Whole_Body_Control",
    "Human_Motion_Reconstruction",
    "Duplicates",
]

# Flip these flags to control which PDF blocks are staged for GitHub.
# Example: only Motion_Generation PDFs are pushed when it is the only True block.
PUSH_PDFS = {
    "Perceptive": False,
    "Locomotion": False,
    "Navigation": False,
    "Loco_Manipulation": False,
    "Motion_Tracking": False,
    "Teleoperation_Data": False,
    "Motion_Generation": True,
    "Whole_Body_Control": False,
    "Human_Motion_Reconstruction": False,
    "Duplicates": False,
}

# Flip these flags to control which Git LFS PDF blocks are fetched by `pull`.
PULL_PDFS = {
    "Perceptive": False,
    "Locomotion": False,
    "Navigation": False,
    "Loco_Manipulation": False,
    "Motion_Tracking": False,
    "Teleoperation_Data": False,
    "Motion_Generation": True,
    "Whole_Body_Control": False,
    "Human_Motion_Reconstruction": False,
    "Duplicates": False,
}

# Safety switch. Leave False and pass --apply when you actually want Git changes.
APPLY_GIT_CHANGES = False

ALWAYS_TRACK_SUFFIXES = {".md", ".txt"}
PDF_SUFFIXES = {".pdf"}
INDEX_MD = "INDEX.md"
PAPERS_TXT = "papers.txt"
GITIGNORE_BEGIN = "# BEGIN pdf-block-manager"
GITIGNORE_END = "# END pdf-block-manager"


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def run(cmd: list[str], *, apply: bool, env: dict[str, str] | None = None) -> None:
    printable = " ".join(cmd)
    if not apply:
        print(f"DRY RUN: {printable}")
        return
    subprocess.run(cmd, cwd=ROOT, env=env, check=True)


def is_pdf(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in PDF_SUFFIXES


def tracked_pdfs(tag: str) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z", f"{tag}/"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
    )
    files = result.stdout.decode("utf-8", errors="replace").split("\0")
    return [f for f in files if f.lower().endswith(".pdf")]


def tag_pdfs(tag: str) -> list[Path]:
    folder = ROOT / tag
    if not folder.exists():
        return []
    return sorted((p for p in folder.rglob("*") if is_pdf(p)), key=lambda p: rel(p).lower())


def tag_text_files(tag: str) -> list[Path]:
    folder = ROOT / tag
    if not folder.exists():
        return []
    return sorted(
        (
            p
            for p in folder.rglob("*")
            if p.is_file() and p.suffix.lower() in ALWAYS_TRACK_SUFFIXES
        ),
        key=lambda p: rel(p).lower(),
    )


def paper_title(path: Path) -> str:
    return path.stem


def write_indexes() -> None:
    for tag in TAG_DIRS:
        folder = ROOT / tag
        if not folder.exists():
            continue

        pdfs = tag_pdfs(tag)
        titles = [paper_title(p) for p in pdfs]
        push_state = "ON" if PUSH_PDFS.get(tag, False) else "OFF"
        pull_state = "ON" if PULL_PDFS.get(tag, False) else "OFF"

        md_lines = [
            f"# {tag}",
            "",
            f"PDF push tracking: {push_state}",
            f"PDF LFS pull: {pull_state}",
            f"PDF count: {len(pdfs)}",
            "",
            "## Papers",
            "",
        ]
        md_lines.extend(f"- {title}" for title in titles)
        (folder / INDEX_MD).write_text("\n".join(md_lines) + "\n", encoding="utf-8")
        (folder / PAPERS_TXT).write_text("\n".join(titles) + ("\n" if titles else ""), encoding="utf-8")
        print(f"wrote {tag}/{INDEX_MD} and {tag}/{PAPERS_TXT}")


def managed_gitignore_block() -> str:
    lines = [
        GITIGNORE_BEGIN,
        "# Generated by tools/pdf_blocks.py.",
        "# Disabled PDF blocks are kept local-only unless their flag is True.",
    ]
    for tag in TAG_DIRS:
        if PUSH_PDFS.get(tag, False):
            continue
        lines.extend(
            [
                f"/{tag}/*.pdf",
                f"/{tag}/*.PDF",
                f"/{tag}/**/*.pdf",
                f"/{tag}/**/*.PDF",
            ]
        )
    lines.append(GITIGNORE_END)
    return "\n".join(lines)


def write_gitignore() -> None:
    path = ROOT / ".gitignore"
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    block = managed_gitignore_block()

    if GITIGNORE_BEGIN in old and GITIGNORE_END in old:
        before, rest = old.split(GITIGNORE_BEGIN, 1)
        _, after = rest.split(GITIGNORE_END, 1)
        new = before.rstrip() + "\n\n" + block + "\n" + after.lstrip()
    else:
        new = old.rstrip() + ("\n\n" if old.strip() else "") + block + "\n"

    path.write_text(new, encoding="utf-8")
    print("wrote .gitignore PDF block")


def stage_metadata(apply: bool) -> None:
    root_files = [
        ".gitattributes",
        ".gitignore",
        "README.md",
        "list.md",
        "list.txt",
        "tools/pdf_blocks.py",
        "new/ToBeAdd.txt",
    ]
    existing = [name for name in root_files if (ROOT / name).exists()]
    text_files = [rel(p) for tag in TAG_DIRS for p in tag_text_files(tag)]
    run(["git", "add", "--", *existing, *text_files], apply=apply)


def stage_pdf_policy(apply: bool) -> None:
    for tag in TAG_DIRS:
        if PUSH_PDFS.get(tag, False):
            pdfs = [rel(p) for p in tag_pdfs(tag)]
            if pdfs:
                run(["git", "add", "-f", "--", *pdfs], apply=apply)
            continue

        disabled = tracked_pdfs(tag)
        if disabled:
            run(["git", "rm", "--cached", "--ignore-unmatch", "--", *disabled], apply=apply)


def stage_for_push(apply: bool) -> None:
    stage_metadata(apply)
    stage_pdf_policy(apply)


def lfs_include_patterns() -> str:
    enabled = [tag for tag in TAG_DIRS if PULL_PDFS.get(tag, False)]
    return ",".join(f"{tag}/**" for tag in enabled)


def pull_lfs_blocks(apply: bool) -> None:
    env = os.environ.copy()
    env["GIT_LFS_SKIP_SMUDGE"] = "1"
    run(["git", "pull"], apply=apply, env=env)

    include = lfs_include_patterns()
    if not include:
        print("No PULL_PDFS blocks are True; skipped git lfs pull.")
        return
    run(["git", "lfs", "pull", "--include", include], apply=apply)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        choices=["indexes", "ignore", "stage", "pull", "sync"],
        help="indexes writes per-tag md/txt; ignore updates .gitignore; stage prepares push; pull fetches selected LFS blocks; sync does indexes+ignore+stage.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually run Git commands. Without this, Git commands are printed only.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    apply = bool(args.apply or APPLY_GIT_CHANGES)

    if args.command in {"indexes", "sync"}:
        write_indexes()
    if args.command in {"ignore", "sync"}:
        write_gitignore()
    if args.command in {"stage", "sync"}:
        stage_for_push(apply)
    if args.command == "pull":
        pull_lfs_blocks(apply)


if __name__ == "__main__":
    main()
